config/routes.rb
# frozen_string_literal: true

AhoyAdmin::Engine.routes.draw do
  root("dashboards#overview")

  get("dashboards/*widget" => "dashboards#widget", :as => :widget_dashboards)
end

app/models/ahoy_admin/application_record.rb
# frozen_string_literal: true

module AhoyAdmin
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/controllers/ahoy_admin/application_controller.rb
# frozen_string_literal: true

module AhoyAdmin
  class ApplicationController < ActionController::Base
  end
end

app/controllers/ahoy_admin/dashboards_controller.rb
# frozen_string_literal: true

module AhoyAdmin
  class DashboardsController < AhoyAdmin::ApplicationController
    before_action(:verify_widget, only: :widget)
    before_action(:verify_period)
    around_action(:set_time_zone)

    PERIODS = [
      %i[today last-24-hours yesterday],
      %i[this-week last-7-days],
      %i[this-month last-30-days last-90-days this-year]
    ].freeze

    def overview
      @presenter = AhoyAdmin::OverviewPresenter.new(current_period: current_period)
    end

    def widget
      send(current_widget)
    end

    AhoyAdmin::Engine.config.widgets.each do |widget|
      define_method(widget) do
        @presenter = "AhoyAdmin::#{widget.classify}Presenter".constantize.new(
          current_period: current_period,
          ref: params[:ref],
          page: params[:page]
        )
        render(:presenter)
      end
    end

    protected

    attr_reader(:presenter)

    helper_method(:presenter)

    def set_time_zone(&block)
      Time.use_zone(AhoyAdmin::Engine.config.time_zone, &block)
    end

    def verify_widget
      return true if current_widget.in?(AhoyAdmin::Engine.config.widgets)

      render(plain: "Not Found", status: :not_found) && false
    end

    def verify_period
      return true if params[:period].blank?
      return true if PERIODS.flatten.include?(params[:period].to_sym)

      redirect_to(root_path)

      false
    end

    def current_widget
      @current_widget ||= params[:widget].to_s.underscore
    end

    def current_period
      params[:period]&.gsub("-", "_")&.to_sym || :last_7_days
    end
  end
end

app/helpers/ahoy_admin/application_helper.rb
# frozen_string_literal: true

module AhoyAdmin
  module ApplicationHelper
    include Pagy::Frontend

    def link_to_period(tag)
      active = params[:period]&.to_sym == tag || params[:period].blank? && tag == :"last-7-days" ? "bg-secondary text-white" : "text-muted"
      link_to(tag.to_s.titleize, url_for(period: tag, url: params[:url]), class: "px-4 py-1 d-block #{active}")
    end

    def ahoy_admin_chart_column(chart_id, chart_data)
      result = "".html_safe
      result += content_tag(:div, "", id: chart_id)
      result +=
        nonced_javascript_tag do
          <<-JS.html_safe
        (function(o){
          o.id = "#{chart_id}"
          o.data = #{chart_data.html_safe};
          o.opts = {
            width: 472,
            height: 400,
            series: [
              {},
              {
                show: true,
                spanGaps: false,
                label: "Value",
                stroke: "#198754",
                fill: "#a3cfbb",
                paths: uPlot.paths.bars({}),
                width: 2,
              }
            ],
            scales: {},
            axes: [
              {},
              {}
            ],
          };
          o.uplot = new uPlot(o.opts, o.data, document.getElementById(o.id));
          chartResize(o.uplot, o.id);
          window.addEventListener("resize", window.throttle(() => chartResize(o.uplot, o.id), 200));
        })(namespace("chart.#{chart_id}"));
          JS
        end
      result
    end

    def admin_user?
      AhoyAdmin::Engine.config.current_user_admin.call(ahoy_admin_current_user)
    end

    def ahoy_admin_current_user
      send(AhoyAdmin::Engine.config.current_user_method)
    end
  end
end

app/views/ahoy_admin/dashboards/_presenter_collection.html.slim
table.table.table-striped.table-sm.table-responsive
  caption.caption-top.text-center
    = link_to presenter.unique_name.titleize, widget_dashboards_path(widget: presenter.unique_name, period: params[:period])
  col width="100%"
  thead
    tr
      th = presenter.dimension.humanize
      th.px-2.text-end = presenter.metric.humanize
      th.px-2.text-end %
  tbody
    - presenter.collection.each do |item|
      tr
        - href = widget_dashboards_path(widget: presenter.unique_name.parameterize, period: params[:period], ref: item.dimension || 'null')
        td.px-2
          a href=href title=presenter.dimension_human(item.dimension)
            = presenter.dimension_human(item.dimension)
          - if presenter.show_dimension_link?
            |&nbsp;&nbsp;
            a href=item.dimension target="_blank"
              svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-link-45deg" viewBox="0 0 16 16"
                path d="M4.715 6.542 3.343 7.914a3 3 0 1 0 4.243 4.243l1.828-1.829A3 3 0 0 0 8.586 5.5L8 6.086a1.002 1.002 0 0 0-.154.199 2 2 0 0 1 .861 3.337L6.88 11.45a2 2 0 1 1-2.83-2.83l.793-.792a4.018 4.018 0 0 1-.128-1.287z"
                path d="M6.586 4.672A3 3 0 0 0 7.414 9.5l.775-.776a2 2 0 0 1-.896-3.346L9.12 3.55a2 2 0 1 1 2.83 2.83l-.793.792c.112.42.155.855.128 1.287l1.372-1.372a3 3 0 1 0-4.243-4.243L6.586 4.672z"

        td.px-2.text-end
          = item.metric
        td.px-2.text-end.text-muted
          = sprintf("%05.2f", item.metric.to_f / presenter.collection_total * 100)

- if pagination
  .d-flex.justify-content-center.m-4.pt-2
    == pagy_bootstrap_nav(presenter.pagy)

app/views/ahoy_admin/dashboards/_presenter_object.html.slim
.px-4.mb-4
  = link_to "back to the list", url_for(ref: nil, period: params[:period])

h6.px-4.my-4.text-center
  = presenter.dimension.humanize
  |:&nbsp;&nbsp;
  span.text-muted
    = presenter.dimension_human(presenter.ref)

h6.mb-3.text-center
  = presenter.metric.humanize

= ahoy_admin_chart_column(presenter.chart_html_id, presenter.data_chart)

table.table.table-striped.table-sm.mt-4
  caption.caption-top.text-center
    |Data Table
  col
  col width="100%"
  thead
    tr
      th.px-2.text-end #
      th.px-2 Date
      th.px-2.text-end = presenter.metric.to_s.humanize
  tbody
    - presenter.object.each.with_index do |data, idx|
      tr
        td.px-2.text-muted = sprintf("%02d", idx + 1)
        td.px-2 = data[0].to_s(:long)
        td.px-2.text-end.text-muted = data[1]

app/views/ahoy_admin/dashboards/overview.html.slim
table.table.table-bordered.text-end.mb-4
  thead
    tr
      th Visits
      th Views
      th Bounce Rate
      th Avg Session
  tbody
    tr
      td = @presenter.total_visits
      td = @presenter.total_views
      td = "#{@presenter.total_bounce_rates}%"
      td = "#{@presenter.total_avg_session_durations}s"

.row
  .col-12.col-xxl-6.mb-4
    h6.text-center Visits
    = ahoy_admin_chart_column("chart-visits", @presenter.chart_visits.to_json)
  .col-12.col-xxl-6
    h6.text-center Views
    = ahoy_admin_chart_column("chart-views", @presenter.chart_views.to_json)
  .col-12.col-xxl-6.mb-4
    h6.text-center Bounce Rate (%)
    = ahoy_admin_chart_column("chart-bounce-rate", @presenter.chart_bounce_rates.to_json)
  .col-12.col-xxl-6.mb-4
    h6.text-center Avg Session Duration (seconds)
    = ahoy_admin_chart_column("chart-avg-session", @presenter.chart_avg_session_durations.to_json)
  .col-12.col-xxl-6.my-4
    = render partial: "presenter_collection", locals: { presenter: @presenter.views_by_page, pagination: false }
  .col-12.col-xxl-6.my-4
    = render partial: "presenter_collection", locals: { presenter: @presenter.visits_by_referrer, pagination: false }
  .col-12.col-xxl-6.my-4
    = render partial: "presenter_collection", locals: { presenter: @presenter.visits_by_country, pagination: false }
  .col-12.col-xxl-6.my-4
    = render partial: "presenter_collection", locals: { presenter: @presenter.visits_by_bot, pagination: false }
    = render partial: "presenter_collection", locals: { presenter: @presenter.visits_by_device, pagination: false }

app/views/ahoy_admin/dashboards/presenter.html.slim
- if presenter.ref
  = render partial: "presenter_object", locals: { presenter: presenter}
- else
  = render partial: "presenter_collection", locals: { presenter: presenter, pagination: true }

app/views/layouts/ahoy_admin/application.html.slim
doctype html
html
  head
    title
      = AhoyAdmin::Engine.config.head_title

    meta name="viewport" content="width=device-width,initial-scale=1"
    - if AhoyAdmin::Engine.config.head_meta_noindex
      meta name="robots" content="noindex"
    - else
      meta name="description" content=AhoyAdmin::Engine.config.head_meta_description
      meta name="keywords" content=AhoyAdmin::Engine.config.head_meta_keywords

    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag "ahoy_admin/application", media: "all"
    = javascript_include_tag "ahoy_admin/application"

    = javascript_include_tag "https://cdn.jsdelivr.net/npm/uplot@1.6.7/dist/uPlot.iife.min.js"
    link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uplot@1.6.7/dist/uPlot.min.css"

    link rel="icon" type="image/png" href=AhoyAdmin::Engine.config.head_favicon_url
  body
    nav.navbar.navbar-expand-lg.navbar-light.bg-light.mb-4
      .container
        a.navbar-brand href="/"
          = AhoyAdmin::Engine.config.brand_name
        /button.navbar-toggler data-bs-toggle="collapse" type="button"
          span.navbar-toggler-icon
        .collapse.navbar-collapse
          ul.navbar-nav.me-auto.mb-2.mb-lg-0
            li.nav-item
              a.nav-link href=root_path Overview
            /li.nav-item
              a.nav-link href="#"  Link
            /li.nav-item
              a.nav-link.disabled aria-disabled="true" href="#" tabindex="-1"  Disabled
            /li.nav-item.dropdown
              a.nav-link.dropdown-toggle aria-expanded="false" data-bs-toggle="dropdown" href="#"  Dropdown
              ul.dropdown-menu
                li
                  a.dropdown-item href="#"  Action
                li
                  a.dropdown-item href="#"  Another action
                li
                  a.dropdown-item href="#"  Something else here


    .container
      .row
        .col-xl-3.mb-4
          - AhoyAdmin::DashboardsController::PERIODS.each_with_index do |period_group, index|
            - period_group.each do |period|
              = link_to_period period
            - if index < (AhoyAdmin::DashboardsController::PERIODS.size - 1)
              hr
        .col-xl-9.mb-4
          = yield